module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V3.Types exposing (State(..))
import Lamdera.Migrations exposing (..)
import SeqDict


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V3.Types.BackendModel
migrate_Types_BackendModel old =
    { rooms = (SeqDict.empty {- Type `SeqDict (Evergreen.V3.Types.RoomId) (Evergreen.V3.Types.Room)` was added in V3. I need you to set a default value. -})
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , state = (RoomSelect { input = "", inputSubmitted = False } {- Type `Evergreen.V3.Types.State` was added in V3. I need you to set a default value. -})
    }


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V3.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.NoOpBackendMsg ->
            Evergreen.V3.Types.NoOpBackendMsg

        Evergreen.V1.Types.ClientConnected _ ->
            Evergreen.V3.Types.NoOpBackendMsg


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V3.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V3.Types.UrlChanged p0

        Evergreen.V1.Types.ShowAll ->
            (Evergreen.V3.Types.RoomMsg Evergreen.V3.Types.ShowAll
             {- `ShowAll` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.ShowAll value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.HideAll ->
            (Evergreen.V3.Types.NoOpFrontendMsg
             {- `HideAll` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.HideAll value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.Edit ->
            (Evergreen.V3.Types.RoomMsg Evergreen.V3.Types.Edit
             {- `Edit` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.Edit value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.ChangedInput p0 p1 ->
            (Evergreen.V3.Types.NoOpFrontendMsg
             {- `ChangedInput` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.ChangedInput value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.Show p0 ->
            (Evergreen.V3.Types.NoOpFrontendMsg
             {- `Show` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.Show value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.ChangeRole p0 ->
            (Evergreen.V3.Types.NoOpFrontendMsg
             {- `ChangeRole` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.ChangeRole value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.Unveil ->
            (Evergreen.V3.Types.RoomMsg Evergreen.V3.Types.Unveil
             {- `Unveil` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.Unveil value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.Veil ->
            (Evergreen.V3.Types.RoomMsg Evergreen.V3.Types.Veil
             {- `Veil` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.Veil value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V3.Types.NoOpFrontendMsg


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V3.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.NoOpToBackend ->
            (Evergreen.V3.Types.NoOpToBackend
             {- `NoOpToBackend` was removed or renamed in V3 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.NoOpToBackend value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.SetConstraints p0 ->
            Evergreen.V3.Types.NoOpToBackend


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V3.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.NoOpToFrontend ->
            Evergreen.V3.Types.NoOpToFrontend

        Evergreen.V1.Types.SendConstraintsToFrontend p0 ->
            Evergreen.V3.Types.NoOpToFrontend
