module Evergreen.Migrate.V8 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V7.Types
import Evergreen.V8.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V7.Types.FrontendModel -> ModelMigration Evergreen.V8.Types.FrontendModel Evergreen.V8.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V7.Types.BackendModel -> ModelMigration Evergreen.V8.Types.BackendModel Evergreen.V8.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V7.Types.FrontendMsg -> MsgMigration Evergreen.V8.Types.FrontendMsg Evergreen.V8.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V7.Types.ToBackend -> MsgMigration Evergreen.V8.Types.ToBackend Evergreen.V8.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V7.Types.BackendMsg -> MsgMigration Evergreen.V8.Types.BackendMsg Evergreen.V8.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V7.Types.ToFrontend -> MsgMigration Evergreen.V8.Types.ToFrontend Evergreen.V8.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V7.Types.FrontendModel -> Evergreen.V8.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , state = old.state |> migrate_Types_State
    }


migrate_Types_AdminFailureReason : Evergreen.V7.Types.AdminFailureReason -> Evergreen.V8.Types.AdminFailureReason
migrate_Types_AdminFailureReason old =
    case old of
        Evergreen.V7.Types.NotLoggedIn ->
            Evergreen.V8.Types.NotLoggedIn

        Evergreen.V7.Types.InvalidPassword ->
            Evergreen.V8.Types.InvalidPassword


migrate_Types_AdminModel : Evergreen.V7.Types.AdminModel -> Evergreen.V8.Types.AdminModel
migrate_Types_AdminModel old =
    { rooms = old.rooms |> List.map migrate_Types_RoomForAdmin
    , now = old.now
    , requiresAdminPassword = old.requiresAdminPassword
    , passwordWasInvalid = old.passwordWasInvalid
    , adminPassword = old.adminPassword
    }


migrate_Types_AdminMsg : Evergreen.V7.Types.AdminMsg -> Evergreen.V8.Types.AdminMsg
migrate_Types_AdminMsg old =
    case old of
        Evergreen.V7.Types.GotRooms p0 p1 ->
            Evergreen.V8.Types.GotRooms (p0 |> List.map migrate_Types_RoomForAdmin) p1

        Evergreen.V7.Types.UserChangedPassword p0 ->
            Evergreen.V8.Types.UserChangedPassword p0

        Evergreen.V7.Types.UserSubmittedPassword ->
            Evergreen.V8.Types.UserSubmittedPassword

        Evergreen.V7.Types.DeleteRoomClicked p0 ->
            Evergreen.V8.Types.DeleteRoomClicked (p0 |> migrate_Types_RoomId)


migrate_Types_AudienceRoomModel : Evergreen.V7.Types.AudienceRoomModel -> Evergreen.V8.Types.AudienceRoomModel
migrate_Types_AudienceRoomModel old =
    { roomId = old.roomId |> migrate_Types_RoomId
    , constraintsDisplayed = old.constraintsDisplayed
    , constraints = old.constraints |> migrate_Types_RoomConstraints
    , waitingForConstraints = (False {- Type `Bool` was added in V8. I need you to set a default value. -})
    }


migrate_Types_BackendMsg : Evergreen.V7.Types.BackendMsg -> Evergreen.V8.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V7.Types.NoOpBackendMsg ->
            Evergreen.V8.Types.NoOpBackendMsg

        Evergreen.V7.Types.OnDisconnect p0 ->
            Evergreen.V8.Types.OnDisconnect p0

        Evergreen.V7.Types.BackendGotTime p0 p1 p2 p3 ->
            Evergreen.V8.Types.BackendGotTime p0 p1 (p2 |> migrate_Types_ToBackend) p3


migrate_Types_Color : Evergreen.V7.Types.Color -> Evergreen.V8.Types.Color
migrate_Types_Color old =
    case old of
        Evergreen.V7.Types.Blue ->
            Evergreen.V8.Types.Blue

        Evergreen.V7.Types.Yellow ->
            Evergreen.V8.Types.Yellow

        Evergreen.V7.Types.Red ->
            Evergreen.V8.Types.Red

        Evergreen.V7.Types.Green ->
            Evergreen.V8.Types.Green


migrate_Types_FrontendMsg : Evergreen.V7.Types.FrontendMsg -> Evergreen.V8.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V7.Types.UrlClicked p0 ->
            Evergreen.V8.Types.UrlClicked p0

        Evergreen.V7.Types.UrlChanged p0 ->
            Evergreen.V8.Types.UrlChanged p0

        Evergreen.V7.Types.RoomSelectMsg p0 ->
            Evergreen.V8.Types.RoomSelectMsg (p0 |> migrate_Types_RoomSelectMsg)

        Evergreen.V7.Types.RoomMsg p0 ->
            Evergreen.V8.Types.RoomMsg (p0 |> migrate_Types_RoomMsg)

        Evergreen.V7.Types.RoomAsHostMsg p0 ->
            Evergreen.V8.Types.RoomAsHostMsg (p0 |> migrate_Types_RoomAsHostMsg)

        Evergreen.V7.Types.RandomPageMsg p0 ->
            Evergreen.V8.Types.RandomPageMsg (p0 |> migrate_Types_RandomPageMsg)

        Evergreen.V7.Types.AdminMsg p0 ->
            Evergreen.V8.Types.AdminMsg (p0 |> migrate_Types_AdminMsg)

        Evergreen.V7.Types.NoOpFrontendMsg ->
            Evergreen.V8.Types.NoOpFrontendMsg


migrate_Types_Mode : Evergreen.V7.Types.Mode -> Evergreen.V8.Types.Mode
migrate_Types_Mode old =
    case old of
        Evergreen.V7.Types.Editing ->
            Evergreen.V8.Types.Editing

        Evergreen.V7.Types.ShowingAll ->
            Evergreen.V8.Types.ShowingAll

        Evergreen.V7.Types.Showing p0 ->
            Evergreen.V8.Types.Showing (p0 |> Maybe.map migrate_Types_Color)


migrate_Types_RandomPageModel : Evergreen.V7.Types.RandomPageModel -> Evergreen.V8.Types.RandomPageModel
migrate_Types_RandomPageModel old =
    { input = old.input
    , drawn = old.drawn
    , seed = old.seed
    , nothingLeftToDraw = old.nothingLeftToDraw
    , showInput = (True {- Type `Bool` was added in V8. I need you to set a default value. -})
    }


migrate_Types_RandomPageMsg : Evergreen.V7.Types.RandomPageMsg -> Evergreen.V8.Types.RandomPageMsg
migrate_Types_RandomPageMsg old =
    case old of
        Evergreen.V7.Types.UserChangedInput p0 ->
            Evergreen.V8.Types.UserChangedInput p0

        Evergreen.V7.Types.UserClickedDraw ->
            Evergreen.V8.Types.UserClickedDraw

        Evergreen.V7.Types.UserClickedReset ->
            Evergreen.V8.Types.UserClickedReset

        Evergreen.V7.Types.GotTime p0 ->
            Evergreen.V8.Types.GotTime p0


migrate_Types_RoomAsHostModel : Evergreen.V7.Types.RoomAsHostModel -> Evergreen.V8.Types.RoomAsHostModel
migrate_Types_RoomAsHostModel old =
    { roomId = old.roomId |> migrate_Types_RoomId
    , mode = old.mode |> migrate_Types_Mode
    , constraintsDisplayed = old.constraintsDisplayed
    , constraints = old.constraints |> migrate_Types_RoomConstraints
    }


migrate_Types_RoomAsHostMsg : Evergreen.V7.Types.RoomAsHostMsg -> Evergreen.V8.Types.RoomAsHostMsg
migrate_Types_RoomAsHostMsg old =
    case old of
        Evergreen.V7.Types.ShowAll ->
            Evergreen.V8.Types.ShowAll

        Evergreen.V7.Types.Edit ->
            Evergreen.V8.Types.Edit

        Evergreen.V7.Types.ChangedInput p0 p1 ->
            Evergreen.V8.Types.ChangedInput (p0 |> migrate_Types_Color) p1

        Evergreen.V7.Types.Show p0 ->
            Evergreen.V8.Types.Show (p0 |> Maybe.map migrate_Types_Color)

        Evergreen.V7.Types.Unveil ->
            Evergreen.V8.Types.Unveil

        Evergreen.V7.Types.Veil ->
            Evergreen.V8.Types.Veil


migrate_Types_RoomConstraints : Evergreen.V7.Types.RoomConstraints -> Evergreen.V8.Types.RoomConstraints
migrate_Types_RoomConstraints old =
    old


migrate_Types_RoomForAdmin : Evergreen.V7.Types.RoomForAdmin -> Evergreen.V8.Types.RoomForAdmin
migrate_Types_RoomForAdmin old =
    { id = old.id |> migrate_Types_RoomId
    , lastChangeDate = old.lastChangeDate
    }


migrate_Types_RoomId : Evergreen.V7.Types.RoomId -> Evergreen.V8.Types.RoomId
migrate_Types_RoomId old =
    case old of
        Evergreen.V7.Types.RoomId p0 ->
            Evergreen.V8.Types.RoomId p0


migrate_Types_RoomModel : Evergreen.V7.Types.RoomModel -> Evergreen.V8.Types.RoomModel
migrate_Types_RoomModel old =
    { roomId = old.roomId |> migrate_Types_RoomId
    , constraintsDisplayed = old.constraintsDisplayed
    , color = old.color |> Maybe.map migrate_Types_Color
    , constraints = old.constraints |> migrate_Types_RoomConstraints
    , waitingForConstraints = (False {- Type `Bool` was added in V8. I need you to set a default value. -})
    }


migrate_Types_RoomMsg : Evergreen.V7.Types.RoomMsg -> Evergreen.V8.Types.RoomMsg
migrate_Types_RoomMsg old =
    case old of
        Evergreen.V7.Types.ChangeColor p0 ->
            Evergreen.V8.Types.ChangeColor (p0 |> Maybe.map migrate_Types_Color)


migrate_Types_RoomSelectModel : Evergreen.V7.Types.RoomSelectModel -> Evergreen.V8.Types.RoomSelectModel
migrate_Types_RoomSelectModel old =
    old


migrate_Types_RoomSelectMsg : Evergreen.V7.Types.RoomSelectMsg -> Evergreen.V8.Types.RoomSelectMsg
migrate_Types_RoomSelectMsg old =
    case old of
        Evergreen.V7.Types.ChangedRoomSelectInput p0 ->
            Evergreen.V8.Types.ChangedRoomSelectInput p0

        Evergreen.V7.Types.Submit ->
            Evergreen.V8.Types.Submit


migrate_Types_State : Evergreen.V7.Types.State -> Evergreen.V8.Types.State
migrate_Types_State old =
    case old of
        Evergreen.V7.Types.RoomSelect p0 ->
            Evergreen.V8.Types.RoomSelect (p0 |> migrate_Types_RoomSelectModel)

        Evergreen.V7.Types.InRoom p0 ->
            Evergreen.V8.Types.InRoom (p0 |> migrate_Types_RoomModel)

        Evergreen.V7.Types.InRoomAsHost p0 ->
            Evergreen.V8.Types.InRoomAsHost (p0 |> migrate_Types_RoomAsHostModel)

        Evergreen.V7.Types.InAudienceRoom p0 ->
            Evergreen.V8.Types.InAudienceRoom (p0 |> migrate_Types_AudienceRoomModel)

        Evergreen.V7.Types.RandomPage p0 ->
            Evergreen.V8.Types.RandomPage (p0 |> migrate_Types_RandomPageModel)

        Evergreen.V7.Types.Admin p0 ->
            Evergreen.V8.Types.Admin (p0 |> migrate_Types_AdminModel)

        Evergreen.V7.Types.RouteError ->
            Evergreen.V8.Types.RouteError


migrate_Types_ToBackend : Evergreen.V7.Types.ToBackend -> Evergreen.V8.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V7.Types.NoOpToBackend ->
            Evergreen.V8.Types.NoOpToBackend

        Evergreen.V7.Types.RegisterToRoom p0 ->
            Evergreen.V8.Types.RegisterToRoom (p0 |> migrate_Types_RoomId)

        Evergreen.V7.Types.UnveilConstraints p0 p1 ->
            Evergreen.V8.Types.UnveilConstraints (p0 |> migrate_Types_RoomId)
                (p1 |> migrate_Types_RoomConstraints)

        Evergreen.V7.Types.HideConstraints p0 ->
            Evergreen.V8.Types.HideConstraints (p0 |> migrate_Types_RoomId)

        Evergreen.V7.Types.RequestRooms p0 ->
            Evergreen.V8.Types.RequestRooms p0

        Evergreen.V7.Types.DeleteRoom p0 ->
            Evergreen.V8.Types.DeleteRoom (p0 |> migrate_Types_RoomId)


migrate_Types_ToFrontend : Evergreen.V7.Types.ToFrontend -> Evergreen.V8.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V7.Types.NoOpToFrontend ->
            Evergreen.V8.Types.NoOpToFrontend

        Evergreen.V7.Types.SendConstraintsToFrontend p0 p1 ->
            Evergreen.V8.Types.SendConstraintsToFrontend (p0 |> migrate_Types_RoomConstraints) p1

        Evergreen.V7.Types.HideConstraintsForClient ->
            Evergreen.V8.Types.HideConstraintsForClient

        Evergreen.V7.Types.SendRoomsToClient p0 ->
            Evergreen.V8.Types.SendRoomsToClient (p0 |> Result.mapError migrate_Types_AdminFailureReason >> Result.map (List.map migrate_Types_RoomForAdmin))
